name: Ruby CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  test:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Ruby build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev
        git clone https://github.com/rbenv/ruby-build.git
        cd ruby-build
        sudo ./install.sh
        
    - name: Install Ruby
      run: |
        sudo ruby-build 3.3.6 /opt/hostedtoolcache/Ruby/3.3.6/x64
        sudo touch /opt/hostedtoolcache/Ruby/3.3.6/x64.complete
        echo "/opt/hostedtoolcache/Ruby/3.3.6/x64/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      
    - name: Build site
      run: bundle exec jekyll build
      
    - name: Run tests
      run: |
        bundle exec htmlproofer ./_site \
          --disable-external=true \
          --allow-missing-href=true \
          --ignore-urls="/assets/img/favicons/" \
          --ignore-missing-alt=true